global: 
  resolve_timeout: 5m
  telegram_api_url: "https://api.telegram.org"
  smtp_from: ${ALERTMANAGER_SMTP_FROM}
  smtp_smarthost: ${ALERTMANAGER_SMTP_SMARTHOST}
  smtp_hello: ${ALERTMANAGER_SMTP_HELLO}
  smtp_auth_username: ${ALERTMANAGER_SMTP_AUTH_USERNAME}
  smtp_auth_password: ${ALERTMANAGER_SMTP_AUTH_PASSWORD}
  smtp_require_tls: true

templates:
  - '/etc/alertmanager/*.tmpl'

receivers:
  - name: blackhole
  - name: telegram
    telegram_configs:
      - chat_id: ${ALERTMANAGER_TG_CHAT_ID}
        bot_token: ${ALERTMANAGER_TG_BOT_TOKEN}
        api_url: "https://api.telegram.org"
        parse_mode: HTML
        message: '{{ template "telegram.message" .}}'
  - name: yandex_email
    email_configs:
      - to: ${ALERTMANAGER_TO_CHAT_ID}
        
route:
  group_by: ['ds_id']
  group_wait: 15s
  group_interval: 30s
  repeat_interval: 12h
  receiver: telegram
  routes:
    - receiver: telegram
      matchers:
        - severity="warning"
    - receiver: yandex_email
      matchers:
        - severity="critical"
    - receiver: blackhole
      matchers:
        - alertname="Watchdog"

