services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
      - ./logs/nginx:/var/log/nginx
    ports:
      - "8080:80"
    links:
      - wordpress
    networks:
      - monitoring

  wordpress:
    depends_on:
      - db
    container_name: wordpress
    image: wordpress:latest
    volumes:
      - ./data/html:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    networks:
      - monitoring

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - monitoring
    ports:
      - 3306:3306

  db-exporter:
    image: prom/mysqld-exporter
    container_name: db-exporter
    command:
      - "--mysqld.username=root:${MYSQL_ROOT_PASSWORD}"
      - "--mysqld.address=db:3306"
    ports:
      - 9104:9104
    depends_on:
      - db
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - ./rules.yaml:/etc/prometheus/rules.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=error'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"
    networks:
      - monitoring

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    volumes: 
      - ./blackbox.yml:/config/blackbox.yml
    command:
      - '--config.file=/config/blackbox.yml'
    restart: unless-stopped
    ports:
      - 9115:9115
    depends_on:
      - wordpress
    networks:
      - monitoring

  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/mimir && minio server --quiet /data"]
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
    networks:
      - monitoring

  load-balancer:
    image: nginx:latest
    container_name: load-balancer
    volumes: 
      - ./mimir-config/nginx.conf:/etc/nignx/nginx.conf:ro
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"
    ports:
      - 9009:9009
    networks:
      - monitoring

  mimir-1:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml", "-config.expand-env=true"]
    container_name: mimir-1
    hostname: mimir-1
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./mimir-config/mimir.yaml:/etc/mimir.yaml
      - mimir-1-data:/data
    networks:
      - monitoring

  mimir-2:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml", "-config.expand-env=true"]
    container_name: mimir-2
    hostname: mimir-2
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./mimir-config/mimir.yaml:/etc/mimir.yaml
      - mimir-2-data:/data
    networks:
      - monitoring

  mimir-3:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml", "-config.expand-env=true"]
    container_name: mimir-3
    hostname: mimir-3
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./mimir-config/mimir.yaml:/etc/mimir.yaml
      - mimir-3-data:/data
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    hostname: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager-data:/alertmanager/data
    command: ['--config.file=/etc/alertmanager/config.yaml']
    ports:
      - 9093:9093
    networks:
      - monitoring
    depends_on:
      - prometheus

volumes:
  prometheus_data: {}
  mimir-1-data: {}
  mimir-2-data: {}
  mimir-3-data: {}
  minio-data: {}
  alertmanager-data: {}

networks:
  monitoring:
    driver: bridge
