global:
  scrape_interval: 5s
  external_labels:
    site: "prod"
rule_files:
  - /etc/prometheus/rules.yaml

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'db'
    scrape_interval: 5s
    static_configs:
      - targets: ['db-exporter:9104']

  - job_name: 'blackbox-http_2xx'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - wordpress:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: test/mimir
    static_configs:
      - targets: ["mimir-1:8080"]
        labels:
          pod: "mimir-1"

      - targets: ["mimir-2:8080"]
        labels:
          pod: "mimir-2"


remote_write:
  - url: http://load_balancer:9009/api/v1/push
    headers:
      X-Scope-OrgID: test

